version: '3.9'

services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 9500:80
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL_FILE=/run/secrets/pgadmin_email
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
    secrets:
      - pgadmin_email
      - pgadmin_password
volumes:
  pgadmin_data:
    driver: local

secrets:
  pgadmin_email:
    file: ./pgadmin_email.txt # put admin password in this file
  pgadmin_password:
    file: ./pgadmin_password.txt # put admin password in this file
