version: '3.9'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - mosquitto_config:/mosquitto/config
    - mosquitto_log:/mosquitto/log
    - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    ports:
    - "1883:1883" 

volumes:
  mosquitto_config:
    driver: local
  mosquitto_log:
    driver: local
  mosquitto_data:
    driver: local
