version: '3.9'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
    volumes:
      - "data:/var/lib/postgresql/data"

volumes:
  data:
    driver: local

secrets:
  postgres_password:
    file: ./postgres_password.txt # put admin password in this file
  postgres_user:
    file: ./postgres_user.txt # put admin password in this file

